# Form implementation generated from reading ui file 'form_stat.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QLabel{\n"
"font-size: 11px;\n"
"color: white;\n"
"}\n"
"QDialog{\n"
"background-color: #373737;\n"
"}\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.count_label = QtWidgets.QLabel(Dialog)
        self.count_label.setObjectName("count_label")
        self.verticalLayout_2.addWidget(self.count_label)
        self.mean_label = QtWidgets.QLabel(Dialog)
        self.mean_label.setObjectName("mean_label")
        self.verticalLayout_2.addWidget(self.mean_label)
        self.dispersion_label = QtWidgets.QLabel(Dialog)
        self.dispersion_label.setObjectName("dispersion_label")
        self.verticalLayout_2.addWidget(self.dispersion_label)
        self.mean_quadratic_label = QtWidgets.QLabel(Dialog)
        self.mean_quadratic_label.setObjectName("mean_quadratic_label")
        self.verticalLayout_2.addWidget(self.mean_quadratic_label)
        self.asimmetric_label = QtWidgets.QLabel(Dialog)
        self.asimmetric_label.setObjectName("asimmetric_label")
        self.verticalLayout_2.addWidget(self.asimmetric_label)
        self.xx_label = QtWidgets.QLabel(Dialog)
        self.xx_label.setObjectName("xx_label")
        self.verticalLayout_2.addWidget(self.xx_label)
        self.interval_label = QtWidgets.QLabel(Dialog)
        self.interval_label.setObjectName("interval_label")
        self.verticalLayout_2.addWidget(self.interval_label)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Количество:"))
        self.label_2.setText(_translate("Dialog", "Среднее значение:"))
        self.label_3.setText(_translate("Dialog", "Дисперсия:"))
        self.label_4.setText(_translate("Dialog", "Среднеквадратичное отклонение:   "))
        self.label_5.setText(_translate("Dialog", "Асимметрия:"))
        self.label_6.setText(_translate("Dialog", "Эксцесс:"))
        self.label_7.setText(_translate("Dialog", "Доверительный интервал:"))
        self.count_label.setText(_translate("Dialog", "TextLabel"))
        self.mean_label.setText(_translate("Dialog", "TextLabel"))
        self.dispersion_label.setText(_translate("Dialog", "TextLabel"))
        self.mean_quadratic_label.setText(_translate("Dialog", "TextLabel"))
        self.asimmetric_label.setText(_translate("Dialog", "TextLabel"))
        self.xx_label.setText(_translate("Dialog", "TextLabel"))
        self.interval_label.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
