# Form implementation generated from reading ui file 'form_reg.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(534, 300)
        Dialog.setStyleSheet("QDialog{\n"
"background-color: #373737;\n"
"}\n"
"QLabel{\n"
"font-size: 10px;\n"
"color: white;\n"
"}\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table_reg_2 = QtWidgets.QTableWidget(Dialog)
        self.table_reg_2.setObjectName("table_reg_2")
        self.table_reg_2.setColumnCount(0)
        self.table_reg_2.setRowCount(0)
        self.gridLayout_2.addWidget(self.table_reg_2, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.graphic_reg_2 = QtWidgets.QWidget(Dialog)
        self.graphic_reg_2.setObjectName("graphic_reg_2")
        self.horizontalLayout_3.addWidget(self.graphic_reg_2)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.coef_reg_label_2 = QtWidgets.QLabel(Dialog)
        self.coef_reg_label_2.setObjectName("coef_reg_label_2")
        self.gridLayout_4.addWidget(self.coef_reg_label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.znam_coef_label_2 = QtWidgets.QLabel(Dialog)
        self.znam_coef_label_2.setObjectName("znam_coef_label_2")
        self.gridLayout_4.addWidget(self.znam_coef_label_2, 2, 1, 1, 1)
        self.znam_mod_label_2 = QtWidgets.QLabel(Dialog)
        self.znam_mod_label_2.setObjectName("znam_mod_label_2")
        self.gridLayout_4.addWidget(self.znam_mod_label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"  style=\" font-size:10px\">Значимость модели в целом</p></body></html>"))
        self.coef_reg_label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:10px;\"></span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"  style=\" font-size:10px\">Значимость коэфффициентов<br/></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:10px;\">Коэффициенты регрессии</span></p></body></html>"))
        self.znam_coef_label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:10px;\"></span></p></body></html>"))
        self.znam_mod_label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:10px;\"></span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"  style=\" font-size:10px\">R-квадрат</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"  style=\" font-size:10px\"></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
